# Site settings
title: Jon Duckworth | GIS Analyst & Developer
description: Professional portfolio and blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
sass:
  sass_dir: _sass

# User settings
username: Jon Duckworth
user_description:
user_title: GIS Analyst & Developer
email: duckontheweb@gmail.com
twitter_username: justducky1981
github_username:  duckontheweb

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
